### ISSUE TITLE
Vagrant box

### ISSUE THREAD

**Issue by gmcgibbon** [winnipegrb/just_chew#10]
Let's make a Vagrant box so people new to Ruby/Rails don't need to waste time with environment setup.

**Comment by dbernar1** [comment]
Let's! :)

What do you think of this one?

https://github.com/lcreid/rails-5-jade/blob/master/README.md

**Comment by gmcgibbon** [comment]
LGTM. I'll test it with the project and report back tomorrow. Thanks for the suggestion!

**Comment by dbernar1** [comment]
You're welcome. I just googled it...

**Comment by gmcgibbon** [comment]
Looks like the Ruby versions don't match and I don't see a version manager. I'm going to try building a box with https://railsbox.io/.
