### ISSUE TITLE
Issues When Using Vagrant

### ISSUE THREAD

**Issue by stungeye** [winnipegrb/just_chew#16]
Using the provided Vagrantfile I was unable to run ruby or bundler from the project folder. The error I was getting was:

    ' is not installed3.1
    ' is not installed3.1

My Google foo failed me so I switch to another Vagrant box using the [bivee/rails box](https://atlas.hashicorp.com/bivee/boxes/rails).

Ran into two issues here but was able to solve them:

### 1) PhantomJs Dependency on LibFontConfig

Error message: `/home/vagrant/.phantomjs/2.1.1/x86_32-linux/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`

*Solution:* `sudo apt-get install libfontconfig`

### 2) Sqlite3 Database Lock Due to Vagrant Shared Folder

Error message: 

    rails aborted!
    ActiveRecord::Tasks::DatabaseAlreadyExists:
    <snip>
    Errno::ETXTBSY: Text file busy @ unlink_internal - /vagrant/RailsCode/just_chew/db/test.sqlite3
    <snip>

*Solution:* 

Edit the `config/database.yml` file and change the test database location to the OS tmp folder (line 21):

    database: /tmp/test.sqlite3

Required because Vagrant shared folders (at least when Windows is the host OS) is funky.

**Comment by gmcgibbon** [comment]
We're currently working on getting a pre-provisioned base box up on atlas. This should fix the provision problems across Vagrant versions.

Regarding the SQLite trouble, we will be ditching SQLite for PG in future labs. This should avoid any sync problems with Vagrant.

**Comment by stungeye** [comment]
👍
